#!/usr/bin/env bash

# Script to compare two Go binaries and generate go.mod replace directives
# to align dependencies from the second binary to match the first one
# Usage: ./align-deps.sh <reference-binary> <target-binary>

set -e

if [ $# -ne 2 ]; then
    echo "Usage: $0 <reference-binary> <target-binary>"
    echo ""
    echo "  reference-binary: The binary with the desired dependency versions"
    echo "  target-binary:    The binary to align with the reference"
    echo ""
    echo "This script will:"
    echo "  1. Extract dependencies from both binaries using 'go version -m'"
    echo "  2. Compare versions of common dependencies"
    echo "  3. Generate go.mod replace directives for mismatched versions"
    exit 1
fi

REFERENCE_BINARY="$1"
TARGET_BINARY="$2"

if [ ! -f "$REFERENCE_BINARY" ]; then
    echo "Error: Reference binary '$REFERENCE_BINARY' not found"
    exit 1
fi

if [ ! -f "$TARGET_BINARY" ]; then
    echo "Error: Target binary '$TARGET_BINARY' not found"
    exit 1
fi

echo "Analyzing binaries..."
echo "  Reference: $REFERENCE_BINARY"
echo "  Target:    $TARGET_BINARY"
echo ""

# Extract dependencies from both binaries
echo "Extracting dependencies from reference binary..."
REFERENCE_DEPS=$(mktemp)
go version -m "$REFERENCE_BINARY" | grep -E '^\s+dep\s+' | awk '{print $2 " " $3}' > "$REFERENCE_DEPS"

echo "Extracting dependencies from target binary..."
TARGET_DEPS=$(mktemp)
go version -m "$TARGET_BINARY" | grep -E '^\s+dep\s+' | awk '{print $2 " " $3}' > "$TARGET_DEPS"

# Create associative arrays to store versions
declare -A reference_versions
declare -A target_versions

# Read reference dependencies
while read -r module version; do
    reference_versions["$module"]="$version"
done < "$REFERENCE_DEPS"

# Read target dependencies
while read -r module version; do
    target_versions["$module"]="$version"
done < "$TARGET_DEPS"

# Find mismatched versions
echo "Comparing dependency versions..."
echo ""

MISMATCHES=()
MISMATCH_COUNT=0

for module in "${!target_versions[@]}"; do
    target_version="${target_versions[$module]}"
    reference_version="${reference_versions[$module]}"

    # Check if module exists in both and versions differ
    if [ -n "$reference_version" ] && [ "$reference_version" != "$target_version" ]; then
        echo "  $module"
        echo "    Reference: $reference_version"
        echo "    Target:    $target_version"
        MISMATCHES+=("$module|$target_version|$reference_version")
        ((MISMATCH_COUNT++))
    fi
done

# Cleanup temp files
rm -f "$REFERENCE_DEPS" "$TARGET_DEPS"

if [ $MISMATCH_COUNT -eq 0 ]; then
    echo "No version mismatches found. Dependencies are already aligned."
    exit 0
fi

echo ""
echo "Found $MISMATCH_COUNT mismatched dependencies."
echo ""
echo "Generating go.mod replace directives..."
echo ""
echo "# Add these replace directives to your go.mod file:"
echo "# Generated by align-deps.sh on $(date)"
echo ""

for mismatch in "${MISMATCHES[@]}"; do
    IFS='|' read -r module target_version reference_version <<< "$mismatch"
    echo "replace $module $target_version => $module $reference_version"
done

echo ""
echo "To apply these changes:"
echo "  1. Copy the replace directives above to your go.mod file"
echo "  2. Run 'go mod tidy' to update dependencies"
echo "  3. Rebuild your target binary"